var music = {
  
  diff(arrays) {
    var items = [].concat.apply(this, arguments);
    var diff = [].slice.call(items), i, l, x, pos;

    for (x = 0, i = 0, l = items.length; i < l; x = 0, i++) {
      while ((pos = diff.indexOf(items[i])) > -1) {
          diff.splice(pos, 1) && x++;
      }
      if (x === 1) diff.push(items[i]);
    }
    return diff;
  },
  
  notes: [ 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab' ],
  
  chords: {
    A2: [ 'A', 'B', 'Db', 'E' ],
    A5: [ 'A', 'E' ],
    A6: [ 'A', 'Db', 'E', 'Gb' ],
    A7: [ 'A', 'Db', 'E', 'G' ],
    A9: [ 'A', 'B', 'Db', 'E', 'G' ],
    A11: [ 'A', 'B', 'Db', 'D', 'E', 'G' ],
    A13: [ 'A', 'B', 'Db', 'D', 'E', 'Gb', 'G' ],
    Amaj: [ 'A', 'Db', 'E' ],
    Am: [ 'A', 'C', 'E' ],
    Am6: [ 'A', 'C', 'E', 'Gb' ],
    Amaj7: [ 'A', 'Db', 'E', 'Ab' ],
    Am7: [ 'A', 'C', 'E', 'G' ],
    Am7b5: [ 'A', 'C', 'Eb', 'G' ],
    Asus: [ 'A', 'B', 'E' ],
    Asus4: [ 'A', 'D', 'E' ],
    Amaj9: [ 'A', 'B', 'Db', 'E', 'Ab' ],
    Am9: [ 'A', 'B', 'C', 'E', 'G' ],
    Adim: [ 'A', 'C', 'Eb' ],
    Aaug: [ 'A', 'Db', 'F' ],
    Bb2: [ 'Bb', 'C', 'D', 'F' ],
    Bb5: [ 'Bb', 'F' ],
    Bb6: [ 'Bb', 'D', 'F', 'G' ],
    Bb7: [ 'Bb', 'D', 'F', 'Ab' ],
    Bb9: [ 'Bb', 'C', 'D', 'F', 'Ab' ],
    Bb11: [ 'Bb', 'C', 'D', 'Eb', 'F', 'Ab' ],
    Bb13: [ 'Bb', 'C', 'D', 'Eb', 'F', 'G', 'Ab' ],
    Bbmaj: [ 'Bb', 'D', 'F' ],
    Bbm: [ 'Bb', 'Db', 'F' ],
    Bbm6: [ 'Bb', 'Db', 'F', 'G' ],
    Bbmaj7: [ 'Bb', 'D', 'F', 'A' ],
    Bbm7: [ 'Bb', 'Db', 'F', 'Ab' ],
    Bbm7b5: [ 'Bb', 'Db', 'E', 'Ab' ],
    Bbsus: [ 'Bb', 'C', 'F' ],
    Bbsus4: [ 'Bb', 'Eb', 'F' ],
    Bbmaj9: [ 'Bb', 'C', 'D', 'F', 'A' ],
    Bbm9: [ 'Bb', 'C', 'Db', 'F', 'Ab' ],
    Bbdim: [ 'Bb', 'Db', 'E' ],
    Bbaug: [ 'Bb', 'D', 'Gb' ],
    B2: [ 'B', 'Db', 'Eb', 'Gb' ],
    B5: [ 'B', 'Gb' ],
    B6: [ 'B', 'Eb', 'Gb', 'Ab' ],
    B7: [ 'B', 'Eb', 'Gb', 'A' ],
    B9: [ 'B', 'Db', 'Eb', 'Gb', 'A' ],
    B11: [ 'B', 'Db', 'Eb', 'E', 'Gb', 'A' ],
    B13: [ 'B', 'Db', 'Eb', 'E', 'Gb', 'Ab', 'A' ],
    Bmaj: [ 'B', 'Eb', 'Gb' ],
    Bm: [ 'B', 'D', 'Gb' ],
    Bm6: [ 'B', 'D', 'Gb', 'Ab' ],
    Bmaj7: [ 'B', 'Eb', 'Gb', 'Bb' ],
    Bm7: [ 'B', 'D', 'Gb', 'A' ],
    Bm7b5: [ 'B', 'D', 'F', 'A' ],
    Bsus: [ 'B', 'Db', 'Gb' ],
    Bsus4: [ 'B', 'E', 'Gb' ],
    Bmaj9: [ 'B', 'Db', 'Eb', 'Gb', 'Bb' ],
    Bm9: [ 'B', 'Db', 'D', 'Gb', 'A' ],
    Bdim: [ 'B', 'D', 'F' ],
    Baug: [ 'B', 'Eb', 'G' ],
    C2: [ 'C', 'D', 'E', 'G' ],
    C5: [ 'C', 'G' ],
    C6: [ 'C', 'E', 'G', 'A' ],
    C7: [ 'C', 'E', 'G', 'Bb' ],
    C9: [ 'C', 'D', 'E', 'G', 'Bb' ],
    C11: [ 'C', 'D', 'E', 'F', 'G', 'Bb' ],
    C13: [ 'C', 'D', 'E', 'F', 'G', 'A', 'Bb' ],
    Cmaj: [ 'C', 'E', 'G' ],
    Cm: [ 'C', 'Eb', 'G' ],
    Cm6: [ 'C', 'Eb', 'G', 'A' ],
    Cmaj7: [ 'C', 'E', 'G', 'B' ],
    Cm7: [ 'C', 'Eb', 'G', 'Bb' ],
    Cm7b5: [ 'C', 'Eb', 'Gb', 'Bb' ],
    Csus: [ 'C', 'D', 'G' ],
    Csus4: [ 'C', 'F', 'G' ],
    Cmaj9: [ 'C', 'D', 'E', 'G', 'B' ],
    Cm9: [ 'C', 'D', 'Eb', 'G', 'Bb' ],
    Cdim: [ 'C', 'Eb', 'Gb' ],
    Caug: [ 'C', 'E', 'Ab' ],
    Db2: [ 'Db', 'Eb', 'F', 'Ab' ],
    Db5: [ 'Db', 'Ab' ],
    Db6: [ 'Db', 'F', 'Ab', 'Bb' ],
    Db7: [ 'Db', 'F', 'Ab', 'B' ],
    Db9: [ 'Db', 'Eb', 'F', 'Ab', 'B' ],
    Db11: [ 'Db', 'Eb', 'F', 'Gb', 'Ab', 'B' ],
    Db13: [ 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'B' ],
    Dbmaj: [ 'Db', 'F', 'Ab' ],
    Dbm: [ 'Db', 'E', 'Ab' ],
    Dbm6: [ 'Db', 'E', 'Ab', 'Bb' ],
    Dbmaj7: [ 'Db', 'F', 'Ab', 'C' ],
    Dbm7: [ 'Db', 'E', 'Ab', 'B' ],
    Dbm7b5: [ 'Db', 'E', 'G', 'B' ],
    Dbsus: [ 'Db', 'Eb', 'Ab' ],
    Dbsus4: [ 'Db', 'Gb', 'Ab' ],
    Dbmaj9: [ 'Db', 'Eb', 'F', 'Ab', 'C' ],
    Dbm9: [ 'Db', 'Eb', 'E', 'Ab', 'B' ],
    Dbdim: [ 'Db', 'E', 'G' ],
    Dbaug: [ 'Db', 'F', 'A' ],
    D2: [ 'D', 'E', 'Gb', 'A' ],
    D5: [ 'D', 'A' ],
    D6: [ 'D', 'Gb', 'A', 'B' ],
    D7: [ 'D', 'Gb', 'A', 'C' ],
    D9: [ 'D', 'E', 'Gb', 'A', 'C' ],
    D11: [ 'D', 'E', 'Gb', 'G', 'A', 'C' ],
    D13: [ 'D', 'E', 'Gb', 'G', 'A', 'B', 'C' ],
    Dmaj: [ 'D', 'Gb', 'A' ],
    Dm: [ 'D', 'F', 'A' ],
    Dm6: [ 'D', 'F', 'A', 'B' ],
    Dmaj7: [ 'D', 'Gb', 'A', 'Db' ],
    Dm7: [ 'D', 'F', 'A', 'C' ],
    Dm7b5: [ 'D', 'F', 'Ab', 'C' ],
    Dsus: [ 'D', 'E', 'A' ],
    Dsus4: [ 'D', 'G', 'A' ],
    Dmaj9: [ 'D', 'E', 'Gb', 'A', 'Db' ],
    Dm9: [ 'D', 'E', 'F', 'A', 'C' ],
    Ddim: [ 'D', 'F', 'Ab' ],
    Daug: [ 'D', 'Gb', 'Bb' ],
    Eb2: [ 'Eb', 'F', 'G', 'Bb' ],
    Eb5: [ 'Eb', 'Bb' ],
    Eb6: [ 'Eb', 'G', 'Bb', 'C' ],
    Eb7: [ 'Eb', 'G', 'Bb', 'Db' ],
    Eb9: [ 'Eb', 'F', 'G', 'Bb', 'Db' ],
    Eb11: [ 'Eb', 'F', 'G', 'Ab', 'Bb', 'Db' ],
    Eb13: [ 'Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'Db' ],
    Ebmaj: [ 'Eb', 'G', 'Bb' ],
    Ebm: [ 'Eb', 'Gb', 'Bb' ],
    Ebm6: [ 'Eb', 'Gb', 'Bb', 'C' ],
    Ebmaj7: [ 'Eb', 'G', 'Bb', 'D' ],
    Ebm7: [ 'Eb', 'Gb', 'Bb', 'Db' ],
    Ebm7b5: [ 'Eb', 'Gb', 'A', 'Db' ],
    Ebsus: [ 'Eb', 'F', 'Bb' ],
    Ebsus4: [ 'Eb', 'Ab', 'Bb' ],
    Ebmaj9: [ 'Eb', 'F', 'G', 'Bb', 'D' ],
    Ebm9: [ 'Eb', 'F', 'Gb', 'Bb', 'Db' ],
    Ebdim: [ 'Eb', 'Gb', 'A' ],
    Ebaug: [ 'Eb', 'G', 'B' ],
    E2: [ 'E', 'Gb', 'Ab', 'B' ],
    E5: [ 'E', 'B' ],
    E6: [ 'E', 'Ab', 'B', 'Db' ],
    E7: [ 'E', 'Ab', 'B', 'D' ],
    E9: [ 'E', 'Gb', 'Ab', 'B', 'D' ],
    E11: [ 'E', 'Gb', 'Ab', 'A', 'B', 'D' ],
    E13: [ 'E', 'Gb', 'Ab', 'A', 'B', 'Db', 'D' ],
    Emaj: [ 'E', 'Ab', 'B' ],
    Em: [ 'E', 'G', 'B' ],
    Em6: [ 'E', 'G', 'B', 'Db' ],
    Emaj7: [ 'E', 'Ab', 'B', 'Eb' ],
    Em7: [ 'E', 'G', 'B', 'D' ],
    Em7b5: [ 'E', 'G', 'Bb', 'D' ],
    Esus: [ 'E', 'Gb', 'B' ],
    Esus4: [ 'E', 'A', 'B' ],
    Emaj9: [ 'E', 'Gb', 'Ab', 'B', 'Eb' ],
    Em9: [ 'E', 'Gb', 'G', 'B', 'D' ],
    Edim: [ 'E', 'G', 'Bb' ],
    Eaug: [ 'E', 'Ab', 'C' ],
    F2: [ 'F', 'G', 'A', 'C' ],
    F5: [ 'F', 'C' ],
    F6: [ 'F', 'A', 'C', 'D' ],
    F7: [ 'F', 'A', 'C', 'Eb' ],
    F9: [ 'F', 'G', 'A', 'C', 'Eb' ],
    F11: [ 'F', 'G', 'A', 'Bb', 'C', 'Eb' ],
    F13: [ 'F', 'G', 'A', 'Bb', 'C', 'D', 'Eb' ],
    Fmaj: [ 'F', 'A', 'C' ],
    Fm: [ 'F', 'Ab', 'C' ],
    Fm6: [ 'F', 'Ab', 'C', 'D' ],
    Fmaj7: [ 'F', 'A', 'C', 'E' ],
    Fm7: [ 'F', 'Ab', 'C', 'Eb' ],
    Fm7b5: [ 'F', 'Ab', 'B', 'Eb' ],
    Fsus: [ 'F', 'G', 'C' ],
    Fsus4: [ 'F', 'Bb', 'C' ],
    Fmaj9: [ 'F', 'G', 'A', 'C', 'E' ],
    Fm9: [ 'F', 'G', 'Ab', 'C', 'Eb' ],
    Fdim: [ 'F', 'Ab', 'B' ],
    Faug: [ 'F', 'A', 'Db' ],
    Gb2: [ 'Gb', 'Ab', 'Bb', 'Db' ],
    Gb5: [ 'Gb', 'Db' ],
    Gb6: [ 'Gb', 'Bb', 'Db', 'Eb' ],
    Gb7: [ 'Gb', 'Bb', 'Db', 'E' ],
    Gb9: [ 'Gb', 'Ab', 'Bb', 'Db', 'E' ],
    Gb11: [ 'Gb', 'Ab', 'Bb', 'B', 'Db', 'E' ],
    Gb13: [ 'Gb', 'Ab', 'Bb', 'B', 'Db', 'Eb', 'E' ],
    Gbmaj: [ 'Gb', 'Bb', 'Db' ],
    Gbm: [ 'Gb', 'A', 'Db' ],
    Gbm6: [ 'Gb', 'A', 'Db', 'Eb' ],
    Gbmaj7: [ 'Gb', 'Bb', 'Db', 'F' ],
    Gbm7: [ 'Gb', 'A', 'Db', 'E' ],
    Gbm7b5: [ 'Gb', 'A', 'C', 'E' ],
    Gbsus: [ 'Gb', 'Ab', 'Db' ],
    Gbsus4: [ 'Gb', 'B', 'Db' ],
    Gbmaj9: [ 'Gb', 'Ab', 'Bb', 'Db', 'F' ],
    Gbm9: [ 'Gb', 'Ab', 'A', 'Db', 'E' ],
    Gbdim: [ 'Gb', 'A', 'C' ],
    Gbaug: [ 'Gb', 'Bb', 'D' ],
    G2: [ 'G', 'A', 'B', 'D' ],
    G5: [ 'G', 'D' ],
    G6: [ 'G', 'B', 'D', 'E' ],
    G7: [ 'G', 'B', 'D', 'F' ],
    G9: [ 'G', 'A', 'B', 'D', 'F' ],
    G11: [ 'G', 'A', 'B', 'C', 'D', 'F' ],
    G13: [ 'G', 'A', 'B', 'C', 'D', 'E', 'F' ],
    Gmaj: [ 'G', 'B', 'D' ],
    Gm: [ 'G', 'Bb', 'D' ],
    Gm6: [ 'G', 'Bb', 'D', 'E' ],
    Gmaj7: [ 'G', 'B', 'D', 'Gb' ],
    Gm7: [ 'G', 'Bb', 'D', 'F' ],
    Gm7b5: [ 'G', 'Bb', 'Db', 'F' ],
    Gsus: [ 'G', 'A', 'D' ],
    Gsus4: [ 'G', 'C', 'D' ],
    Gmaj9: [ 'G', 'A', 'B', 'D', 'Gb' ],
    Gm9: [ 'G', 'A', 'Bb', 'D', 'F' ],
    Gdim: [ 'G', 'Bb', 'Db' ],
    Gaug: [ 'G', 'B', 'Eb' ],
    Ab2: [ 'Ab', 'Bb', 'C', 'Eb' ],
    Ab5: [ 'Ab', 'Eb' ],
    Ab6: [ 'Ab', 'C', 'Eb', 'F' ],
    Ab7: [ 'Ab', 'C', 'Eb', 'Gb' ],
    Ab9: [ 'Ab', 'Bb', 'C', 'Eb', 'Gb' ],
    Ab11: [ 'Ab', 'Bb', 'C', 'Db', 'Eb', 'Gb' ],
    Ab13: [ 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'Gb' ],
    Abmaj: [ 'Ab', 'C', 'Eb' ],
    Abm: [ 'Ab', 'B', 'Eb' ],
    Abm6: [ 'Ab', 'B', 'Eb', 'F' ],
    Abmaj7: [ 'Ab', 'C', 'Eb', 'G' ],
    Abm7: [ 'Ab', 'B', 'Eb', 'Gb' ],
    Abm7b5: [ 'Ab', 'B', 'D', 'Gb' ],
    Absus: [ 'Ab', 'Bb', 'Eb' ],
    Absus4: [ 'Ab', 'Db', 'Eb' ],
    Abmaj9: [ 'Ab', 'Bb', 'C', 'Eb', 'G' ],
    Abm9: [ 'Ab', 'Bb', 'B', 'Eb', 'Gb' ],
    Abdim: [ 'Ab', 'B', 'D' ],
    Abaug: [ 'Ab', 'C', 'E' ]
  },
  
  scales: {
    A_chromatic: [ 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab' ],
    A_blues: [ 'A', 'C', 'D', 'Eb', 'E', 'G' ],
    A_melodic: [ 'A', 'B', 'Db', 'D', 'E', 'Gb', 'Ab' ],
    A_melodicMin: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G' ],
    A_harmonic: [ 'A', 'B', 'C', 'D', 'E', 'F', 'Ab' ],
    A_harmonicMin: [ 'A', 'B', 'C', 'D', 'E', 'F', 'Ab' ],
    A_pentatonicMaj: [ 'A', 'B', 'Db', 'D', 'Gb' ],
    A_pentatonicMin: [ 'A', 'C', 'D', 'E', 'G' ],
    A_ionian: [ 'A', 'B', 'Db', 'D', 'E', 'Gb', 'Ab' ],
    A_dorian: [ 'A', 'B', 'C', 'D', 'E', 'Gb', 'G' ],
    A_phrygian: [ 'A', 'Bb', 'C', 'D', 'E', 'F', 'G' ],
    A_lydian: [ 'A', 'B', 'Db', 'Eb', 'E', 'Gb', 'Ab' ],
    A_mixolydian: [ 'A', 'B', 'Db', 'D', 'E', 'Gb', 'G' ],
    A_aeolian: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G' ],
    A_locrian: [ 'A', 'Bb', 'C', 'D', 'Eb', 'F', 'G' ],
    Bb_chromatic: [ 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A' ],
    Bb_blues: [ 'Bb', 'Db', 'Eb', 'E', 'F', 'Ab' ],
    Bb_melodic: [ 'Bb', 'C', 'D', 'Eb', 'F', 'G', 'A' ],
    Bb_melodicMin: [ 'Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab' ],
    Bb_harmonic: [ 'Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'A' ],
    Bb_harmonicMin: [ 'Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'A' ],
    Bb_pentatonicMaj: [ 'Bb', 'C', 'D', 'Eb', 'G' ],
    Bb_pentatonicMin: [ 'Bb', 'Db', 'Eb', 'F', 'Ab' ],
    Bb_ionian: [ 'Bb', 'C', 'D', 'Eb', 'F', 'G', 'A' ],
    Bb_dorian: [ 'Bb', 'C', 'Db', 'Eb', 'F', 'G', 'Ab' ],
    Bb_phrygian: [ 'Bb', 'B', 'Db', 'Eb', 'F', 'Gb', 'Ab' ],
    Bb_lydian: [ 'Bb', 'C', 'D', 'E', 'F', 'G', 'A' ],
    Bb_mixolydian: [ 'Bb', 'C', 'D', 'Eb', 'F', 'G', 'Ab' ],
    Bb_aeolian: [ 'Bb', 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab' ],
    Bb_locrian: [ 'Bb', 'B', 'Db', 'Eb', 'E', 'Gb', 'Ab' ],
    B_chromatic: [ 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb' ],
    B_blues: [ 'B', 'D', 'E', 'F', 'Gb', 'A' ],
    B_melodic: [ 'B', 'Db', 'Eb', 'E', 'Gb', 'Ab', 'Bb' ],
    B_melodicMin: [ 'B', 'Db', 'D', 'E', 'Gb', 'G', 'A' ],
    B_harmonic: [ 'B', 'Db', 'D', 'E', 'Gb', 'G', 'Bb' ],
    B_harmonicMin: [ 'B', 'Db', 'D', 'E', 'Gb', 'G', 'Bb' ],
    B_pentatonicMaj: [ 'B', 'Db', 'Eb', 'E', 'Ab' ],
    B_pentatonicMin: [ 'B', 'D', 'E', 'Gb', 'A' ],
    B_ionian: [ 'B', 'Db', 'Eb', 'E', 'Gb', 'Ab', 'Bb' ],
    B_dorian: [ 'B', 'Db', 'D', 'E', 'Gb', 'Ab', 'A' ],
    B_phrygian: [ 'B', 'C', 'D', 'E', 'Gb', 'G', 'A' ],
    B_lydian: [ 'B', 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb' ],
    B_mixolydian: [ 'B', 'Db', 'Eb', 'E', 'Gb', 'Ab', 'A' ],
    B_aeolian: [ 'B', 'Db', 'D', 'E', 'Gb', 'G', 'A' ],
    B_locrian: [ 'B', 'C', 'D', 'E', 'F', 'G', 'A' ],
    C_chromatic: [ 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B' ],
    C_blues: [ 'C', 'Eb', 'F', 'Gb', 'G', 'Bb' ],
    C_melodic: [ 'C', 'D', 'E', 'F', 'G', 'A', 'B' ],
    C_melodicMin: [ 'C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb' ],
    C_harmonic: [ 'C', 'D', 'Eb', 'F', 'G', 'Ab', 'B' ],
    C_harmonicMin: [ 'C', 'D', 'Eb', 'F', 'G', 'Ab', 'B' ],
    C_pentatonicMaj: [ 'C', 'D', 'E', 'F', 'A' ],
    C_pentatonicMin: [ 'C', 'Eb', 'F', 'G', 'Bb' ],
    C_ionian: [ 'C', 'D', 'E', 'F', 'G', 'A', 'B' ],
    C_dorian: [ 'C', 'D', 'Eb', 'F', 'G', 'A', 'Bb' ],
    C_phrygian: [ 'C', 'Db', 'Eb', 'F', 'G', 'Ab', 'Bb' ],
    C_lydian: [ 'C', 'D', 'E', 'Gb', 'G', 'A', 'B' ],
    C_mixolydian: [ 'C', 'D', 'E', 'F', 'G', 'A', 'Bb' ],
    C_aeolian: [ 'C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb' ],
    C_locrian: [ 'C', 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb' ],
    Db_chromatic: [ 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B', 'C' ],
    Db_blues: [ 'Db', 'E', 'Gb', 'G', 'Ab', 'B' ],
    Db_melodic: [ 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C' ],
    Db_melodicMin: [ 'Db', 'Eb', 'E', 'Gb', 'Ab', 'A', 'B' ],
    Db_harmonic: [ 'Db', 'Eb', 'E', 'Gb', 'Ab', 'A', 'C' ],
    Db_harmonicMin: [ 'Db', 'Eb', 'E', 'Gb', 'Ab', 'A', 'C' ],
    Db_pentatonicMaj: [ 'Db', 'Eb', 'F', 'Gb', 'Bb' ],
    Db_pentatonicMin: [ 'Db', 'E', 'Gb', 'Ab', 'B' ],
    Db_ionian: [ 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C' ],
    Db_dorian: [ 'Db', 'Eb', 'E', 'Gb', 'Ab', 'Bb', 'B' ],
    Db_phrygian: [ 'Db', 'D', 'E', 'Gb', 'Ab', 'A', 'B' ],
    Db_lydian: [ 'Db', 'Eb', 'F', 'G', 'Ab', 'Bb', 'C' ],
    Db_mixolydian: [ 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'B' ],
    Db_aeolian: [ 'Db', 'Eb', 'E', 'Gb', 'Ab', 'A', 'B' ],
    Db_locrian: [ 'Db', 'D', 'E', 'Gb', 'G', 'A', 'B' ],
    D_chromatic: [ 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db' ],
    D_blues: [ 'D', 'F', 'G', 'Ab', 'A', 'C' ],
    D_melodic: [ 'D', 'E', 'Gb', 'G', 'A', 'B', 'Db' ],
    D_melodicMin: [ 'D', 'E', 'F', 'G', 'A', 'Bb', 'C' ],
    D_harmonic: [ 'D', 'E', 'F', 'G', 'A', 'Bb', 'Db' ],
    D_harmonicMin: [ 'D', 'E', 'F', 'G', 'A', 'Bb', 'Db' ],
    D_pentatonicMaj: [ 'D', 'E', 'Gb', 'G', 'B' ],
    D_pentatonicMin: [ 'D', 'F', 'G', 'A', 'C' ],
    D_ionian: [ 'D', 'E', 'Gb', 'G', 'A', 'B', 'Db' ],
    D_dorian: [ 'D', 'E', 'F', 'G', 'A', 'B', 'C' ],
    D_phrygian: [ 'D', 'Eb', 'F', 'G', 'A', 'Bb', 'C' ],
    D_lydian: [ 'D', 'E', 'Gb', 'Ab', 'A', 'B', 'Db' ],
    D_mixolydian: [ 'D', 'E', 'Gb', 'G', 'A', 'B', 'C' ],
    D_aeolian: [ 'D', 'E', 'F', 'G', 'A', 'Bb', 'C' ],
    D_locrian: [ 'D', 'Eb', 'F', 'G', 'Ab', 'Bb', 'C' ],
    Eb_chromatic: [ 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D' ],
    Eb_blues: [ 'Eb', 'Gb', 'Ab', 'A', 'Bb', 'Db' ],
    Eb_melodic: [ 'Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D' ],
    Eb_melodicMin: [ 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'B', 'Db' ],
    Eb_harmonic: [ 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'B', 'D' ],
    Eb_harmonicMin: [ 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'B', 'D' ],
    Eb_pentatonicMaj: [ 'Eb', 'F', 'G', 'Ab', 'C' ],
    Eb_pentatonicMin: [ 'Eb', 'Gb', 'Ab', 'Bb', 'Db' ],
    Eb_ionian: [ 'Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D' ],
    Eb_dorian: [ 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C', 'Db' ],
    Eb_phrygian: [ 'Eb', 'E', 'Gb', 'Ab', 'Bb', 'B', 'Db' ],
    Eb_lydian: [ 'Eb', 'F', 'G', 'A', 'Bb', 'C', 'D' ],
    Eb_mixolydian: [ 'Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'Db' ],
    Eb_aeolian: [ 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'B', 'Db' ],
    Eb_locrian: [ 'Eb', 'E', 'Gb', 'Ab', 'A', 'B', 'Db' ],
    E_chromatic: [ 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb' ],
    E_blues: [ 'E', 'G', 'A', 'Bb', 'B', 'D' ],
    E_melodic: [ 'E', 'Gb', 'Ab', 'A', 'B', 'Db', 'Eb' ],
    E_melodicMin: [ 'E', 'Gb', 'G', 'A', 'B', 'C', 'D' ],
    E_harmonic: [ 'E', 'Gb', 'G', 'A', 'B', 'C', 'Eb' ],
    E_harmonicMin: [ 'E', 'Gb', 'G', 'A', 'B', 'C', 'Eb' ],
    E_pentatonicMaj: [ 'E', 'Gb', 'Ab', 'A', 'Db' ],
    E_pentatonicMin: [ 'E', 'G', 'A', 'B', 'D' ],
    E_ionian: [ 'E', 'Gb', 'Ab', 'A', 'B', 'Db', 'Eb' ],
    E_dorian: [ 'E', 'Gb', 'G', 'A', 'B', 'Db', 'D' ],
    E_phrygian: [ 'E', 'F', 'G', 'A', 'B', 'C', 'D' ],
    E_lydian: [ 'E', 'Gb', 'Ab', 'Bb', 'B', 'Db', 'Eb' ],
    E_mixolydian: [ 'E', 'Gb', 'Ab', 'A', 'B', 'Db', 'D' ],
    E_aeolian: [ 'E', 'Gb', 'G', 'A', 'B', 'C', 'D' ],
    E_locrian: [ 'E', 'F', 'G', 'A', 'Bb', 'C', 'D' ],
    F_chromatic: [ 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E' ],
    F_blues: [ 'F', 'Ab', 'Bb', 'B', 'C', 'Eb' ],
    F_melodic: [ 'F', 'G', 'A', 'Bb', 'C', 'D', 'E' ],
    F_melodicMin: [ 'F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb' ],
    F_harmonic: [ 'F', 'G', 'Ab', 'Bb', 'C', 'Db', 'E' ],
    F_harmonicMin: [ 'F', 'G', 'Ab', 'Bb', 'C', 'Db', 'E' ],
    F_pentatonicMaj: [ 'F', 'G', 'A', 'Bb', 'D' ],
    F_pentatonicMin: [ 'F', 'Ab', 'Bb', 'C', 'Eb' ],
    F_ionian: [ 'F', 'G', 'A', 'Bb', 'C', 'D', 'E' ],
    F_dorian: [ 'F', 'G', 'Ab', 'Bb', 'C', 'D', 'Eb' ],
    F_phrygian: [ 'F', 'Gb', 'Ab', 'Bb', 'C', 'Db', 'Eb' ],
    F_lydian: [ 'F', 'G', 'A', 'B', 'C', 'D', 'E' ],
    F_mixolydian: [ 'F', 'G', 'A', 'Bb', 'C', 'D', 'Eb' ],
    F_aeolian: [ 'F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb' ],
    F_locrian: [ 'F', 'Gb', 'Ab', 'Bb', 'B', 'Db', 'Eb' ],
    Gb_chromatic: [ 'Gb', 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F' ],
    Gb_blues: [ 'Gb', 'A', 'B', 'C', 'Db', 'E' ],
    Gb_melodic: [ 'Gb', 'Ab', 'Bb', 'B', 'Db', 'Eb', 'F' ],
    Gb_melodicMin: [ 'Gb', 'Ab', 'A', 'B', 'Db', 'D', 'E' ],
    Gb_harmonic: [ 'Gb', 'Ab', 'A', 'B', 'Db', 'D', 'F' ],
    Gb_harmonicMin: [ 'Gb', 'Ab', 'A', 'B', 'Db', 'D', 'F' ],
    Gb_pentatonicMaj: [ 'Gb', 'Ab', 'Bb', 'B', 'Eb' ],
    Gb_pentatonicMin: [ 'Gb', 'A', 'B', 'Db', 'E' ],
    Gb_ionian: [ 'Gb', 'Ab', 'Bb', 'B', 'Db', 'Eb', 'F' ],
    Gb_dorian: [ 'Gb', 'Ab', 'A', 'B', 'Db', 'Eb', 'E' ],
    Gb_phrygian: [ 'Gb', 'G', 'A', 'B', 'Db', 'D', 'E' ],
    Gb_lydian: [ 'Gb', 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F' ],
    Gb_mixolydian: [ 'Gb', 'Ab', 'Bb', 'B', 'Db', 'Eb', 'E' ],
    Gb_aeolian: [ 'Gb', 'Ab', 'A', 'B', 'Db', 'D', 'E' ],
    Gb_locrian: [ 'Gb', 'G', 'A', 'B', 'C', 'D', 'E' ],
    G_chromatic: [ 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb' ],
    G_blues: [ 'G', 'Bb', 'C', 'Db', 'D', 'F' ],
    G_melodic: [ 'G', 'A', 'B', 'C', 'D', 'E', 'Gb' ],
    G_melodicMin: [ 'G', 'A', 'Bb', 'C', 'D', 'Eb', 'F' ],
    G_harmonic: [ 'G', 'A', 'Bb', 'C', 'D', 'Eb', 'Gb' ],
    G_harmonicMin: [ 'G', 'A', 'Bb', 'C', 'D', 'Eb', 'Gb' ],
    G_pentatonicMaj: [ 'G', 'A', 'B', 'C', 'E' ],
    G_pentatonicMin: [ 'G', 'Bb', 'C', 'D', 'F' ],
    G_ionian: [ 'G', 'A', 'B', 'C', 'D', 'E', 'Gb' ],
    G_dorian: [ 'G', 'A', 'Bb', 'C', 'D', 'E', 'F' ],
    G_phrygian: [ 'G', 'Ab', 'Bb', 'C', 'D', 'Eb', 'F' ],
    G_lydian: [ 'G', 'A', 'B', 'Db', 'D', 'E', 'Gb' ],
    G_mixolydian: [ 'G', 'A', 'B', 'C', 'D', 'E', 'F' ],
    G_aeolian: [ 'G', 'A', 'Bb', 'C', 'D', 'Eb', 'F' ],
    G_locrian: [ 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F' ],
    Ab_chromatic: [ 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G' ],
    Ab_blues: [ 'Ab', 'B', 'Db', 'D', 'Eb', 'Gb' ],
    Ab_melodic: [ 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G' ],
    Ab_melodicMin: [ 'Ab', 'Bb', 'B', 'Db', 'Eb', 'E', 'Gb' ],
    Ab_harmonic: [ 'Ab', 'Bb', 'B', 'Db', 'Eb', 'E', 'G' ],
    Ab_harmonicMin: [ 'Ab', 'Bb', 'B', 'Db', 'Eb', 'E', 'G' ],
    Ab_pentatonicMaj: [ 'Ab', 'Bb', 'C', 'Db', 'F' ],
    Ab_pentatonicMin: [ 'Ab', 'B', 'Db', 'Eb', 'Gb' ],
    Ab_ionian: [ 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G' ],
    Ab_dorian: [ 'Ab', 'Bb', 'B', 'Db', 'Eb', 'F', 'Gb' ],
    Ab_phrygian: [ 'Ab', 'A', 'B', 'Db', 'Eb', 'E', 'Gb' ],
    Ab_lydian: [ 'Ab', 'Bb', 'C', 'D', 'Eb', 'F', 'G' ],
    Ab_mixolydian: [ 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'Gb' ],
    Ab_aeolian: [ 'Ab', 'Bb', 'B', 'Db', 'Eb', 'E', 'Gb' ],
    Ab_locrian: [ 'Ab', 'A', 'B', 'Db', 'D', 'E', 'Gb' ]
  },
  
  chordBuild: {
    
    maj: [ 4, 7 ],
    m: [ 3, 7 ],
    2: [ 2, 4, 7],
    5: [ 7 ],
    6: [ 4, 7, 9 ],
    m6: [ 3, 7, 9 ],
    7: [ 4, 7, 10 ],
    maj7: [ 4, 7, 11 ],
    m7: [ 3, 7, 10 ],
    m7b5: [ 3, 6, 10 ],
    sus: [ 2, 7 ],
    sus4: [ 5, 7 ],
    9: [ 2, 4, 7, 10 ],
    maj9: [ 2, 4, 7, 11 ],
    m9: [ 2, 3, 7, 10 ],
    11: [ 2, 4, 5, 7, 10 ],
    13: [ 2, 4, 5, 7, 9, 10 ],
    dim: [ 3, 6 ],
    aug: [ 4, 8 ]
    
  },
  
  scaleBuild: {
    
    chromatic: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ],
    blues: [ 3, 5, 6, 7, 10 ],
    melodic: {
      maj : [ 2, 4, 5, 7, 9, 11 ],
      m: [ 2, 3, 5, 7, 8, 10 ]
    },
    harmonic: {
      maj: [ 2, 3, 5, 7, 8, 11 ],
      m: [ 2, 3, 5, 7, 8, 11 ]
    },
    pentatonic: {
      maj: [ 2, 4, 5, 9 ],
      m: [ 3, 5, 7, 10 ]
    },
    greek: {
      ionian: [ 2, 4, 5, 7, 9, 11 ],
      dorian: [ 2, 3, 5, 7, 9, 10 ],
      phrygian: [ 1, 3, 5, 7, 8, 10 ],
      lydian: [ 2, 4, 6, 7, 9, 11 ],
      mixolydian: [ 2, 4, 5, 7, 9, 10 ],
      aeolian: [ 2, 3, 5, 7, 8, 10 ],
      locrian: [ 1, 3, 5, 6, 8, 10 ]
    }
    
  },
  
  redraw(note, prog) {
    let root = this.notes.indexOf(note);
    let a = [];
    prog.forEach((val, key) => {
      let t = val;
      if(val + root > 11) {
        t = val + root - 12;
        t -= root;
        a.push(t);
      } else {
        a.push(t);
      }
    });
    return a;
  },
  
  chord(note, chord) {
    let root = this.notes.indexOf(note);
    let result = [note];
    let prog = this.redraw(note, chord);
    prog.forEach((val, key) => { result.push(this.notes[root + val]) });
    return result;
    
  },
  
  scale(note, scale) {
    let root = this.notes.indexOf(note);
    let result = [note];
    let prog = this.redraw(note, scale);
    prog.forEach((val, key) => { result.push(this.notes[root + val]) });
    return result;
  },
  
  tritone(note) {
    let root = this.notes.indexOf(note);
    let result = [note];
    let tritone = this.redraw(note, [6]);
    result.push(this.notes[root + tritone[0]]);
    return result;
  }
  
};